oracle_install_group:            "oinstall"
mount_directory:                 "/"
root_directory:                  "/u01"
stage_dir:                       "/u01/stage"
scripts_directory:               "{{ root_directory }}/app/scripts"
oracle_base:                     /oracle
oracle_home:                     /oracle/product/19.0.0/dbhome_1
oracle_inventory:                /oracle/oraInventory 
oracle_user:                     oracle
root_user:                       root
oradbsoft_rsp:                   "19cEE_SoftOnly"    
preinstall_pkg:                  "oracle-database-preinstall-19c-1.0-1.el7.src.rpm"
oracle19c_url:                   "https://127.0.0.1/path/to/file.zip"
